import { useState, useEffect } from 'react';
import axios from 'axios';

const formatCurrency = (amount, currencyCode = 'USD') => {
    if (amount === undefined || amount === null || isNaN(amount)) return '$0.00';
    try { return new Intl.NumberFormat('en-US', { style: 'currency', currency: currencyCode }).format(amount); }
    catch (e) { return `${currencyCode} ${Number(amount).toFixed(2)}`; }
};

// Universal PDF Generator for Finance Team
const handlePrintDocument = (docType, docData) => {
    if (!docData) return alert("Document data not available.");
    const printWindow = window.open('', '', 'width=800,height=900');

    const html = `
        <html>
        <head>
            <title>${docType} Document</title>
            <style>
                body { font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif; color: #333; padding: 40px; }
                .header { display: flex; justify-content: space-between; border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 20px; }
                .header h1 { margin: 0; color: #2563eb; font-size: 32px; text-transform: uppercase; }
                .info-section { display: flex; justify-content: space-between; margin-bottom: 30px; }
                .info-box { width: 45%; }
                .info-box h3 { font-size: 12px; color: #64748b; text-transform: uppercase; border-bottom: 1px solid #e2e8f0; padding-bottom: 5px; margin-bottom: 10px; }
                .info-box p { margin: 5px 0; font-size: 14px; white-space: pre-wrap; }
                table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
                th { background-color: #f8fafc; color: #475569; text-transform: uppercase; font-size: 12px; padding: 12px; text-align: left; border-bottom: 2px solid #cbd5e1; }
                td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 14px; }
                .text-right { text-align: right; }
                .summary { width: 50%; float: right; }
                .summary-row { display: flex; justify-content: space-between; padding: 10px 0; font-size: 14px; }
                .summary-total { font-weight: bold; font-size: 18px; border-top: 2px solid #000; margin-top: 5px; padding-top: 10px; }
            </style>
        </head>
        <body>
            <div class="header">
                <div>
                    <h1>${docType}</h1>
                    <p><strong>Document Number:</strong> ${docData.invoiceNumber || docData.poNumber || 'Generated Data'}</p>
                    <p><strong>Date:</strong> ${docData.invoiceDate || docData.poDate || new Date().toLocaleDateString()}</p>
                </div>
                <div style="text-align: right;">
                    <h2 style="margin:0; color:#1e293b;">Nestle Enterprise</h2>
                </div>
            </div>
            <div class="info-section">
                <div class="info-box">
                    <h3>Vendor Details</h3>
                    <p><strong>${docData.vendorName || 'Unknown'}</strong><br/>${docData.vendorAddress || 'No Address Provided'}</p>
                </div>
                <div class="info-box">
                    <h3>Billing Details</h3>
                    <p>${docData.billTo || 'Nestle Finance Command Center'}</p>
                </div>
            </div>
            <table>
                <thead><tr><th>Qty</th><th>Description</th><th class="text-right">Unit Price</th><th class="text-right">Total</th></tr></thead>
                <tbody>
                    ${(docData.lineItems || []).map(item => `<tr><td>${item.qty}</td><td>${item.description}</td><td class="text-right">${formatCurrency(item.unitPrice, docData.currency)}</td><td class="text-right">${formatCurrency(item.amount, docData.currency)}</td></tr>`).join('')}
                </tbody>
            </table>
            <div class="summary">
                <div class="summary-row"><span>Subtotal:</span> <span>${formatCurrency(docData.subtotal, docData.currency)}</span></div>
                <div class="summary-row"><span>Taxes:</span> <span>${formatCurrency(docData.salesTax, docData.currency)}</span></div>
                <div class="summary-row summary-total"><span>Total Payable:</span> <span>${formatCurrency(docData.totalAmount, docData.currency)}</span></div>
            </div>
            <p style="margin-top: 40px; text-align: center; color: #94a3b8; font-size: 12px;">Generated by Nestle AI Extractor | <em>Click 'Save as PDF' in the print dialog.</em></p>
        </body>
        </html>
    `;
    printWindow.document.write(html);
    printWindow.document.close();
    printWindow.focus();
    setTimeout(() => { printWindow.print(); }, 500);
};

export default function Portal({ user, onLogout }) {
    const [activeTab, setActiveTab] = useState('procurement');
    const [isDarkMode, setIsDarkMode] = useState(true);

    useEffect(() => {
        if (isDarkMode) document.documentElement.classList.add('dark');
        else document.documentElement.classList.remove('dark');
    }, [isDarkMode]);

    return (
        <div className="min-h-screen flex flex-col md:flex-row bg-slate-50 dark:bg-slate-950 transition-colors duration-300">
            <div className="md:w-64 bg-slate-900 text-slate-300 flex flex-col shadow-2xl z-10 shrink-0">
                <div className="p-6 border-b border-slate-800">
                    <h1 className="text-xl font-black text-white tracking-tight">Nestle<span className="text-blue-500">Finance</span></h1>
                    <p className="text-xs text-slate-500 mt-1 uppercase tracking-wider font-bold">User: {user.id?.slice(0, 8) || user.email}</p>
                </div>

                <div className="flex-grow py-6 flex flex-col gap-2 px-4 overflow-y-auto">
                    <p className="text-xs font-bold text-slate-500 uppercase px-4 mb-2">Dashboards</p>
                    <button onClick={() => setActiveTab('procurement')} className={`text-left px-4 py-3 rounded-xl font-medium transition-all ${activeTab === 'procurement' ? 'bg-blue-600 text-white shadow-md' : 'hover:bg-slate-800 hover:text-white'}`}>
                        🛒 Procurement (BOQ)
                    </button>
                    <button onClick={() => setActiveTab('finance')} className={`text-left px-4 py-3 rounded-xl font-medium transition-all ${activeTab === 'finance' ? 'bg-blue-600 text-white shadow-md' : 'hover:bg-slate-800 hover:text-white'}`}>
                        📋 Review Queue
                    </button>
                    <button onClick={() => setActiveTab('analytics')} className={`text-left px-4 py-3 rounded-xl font-medium transition-all ${activeTab === 'analytics' ? 'bg-blue-600 text-white shadow-md' : 'hover:bg-slate-800 hover:text-white'}`}>
                        📈 Analytics
                    </button>
                </div>

                <div className="p-4 border-t border-slate-800 space-y-2">
                    <button onClick={() => setIsDarkMode(!isDarkMode)} className="w-full py-2 bg-slate-800 hover:bg-slate-700 rounded-lg text-sm font-bold text-white transition-colors">
                        {isDarkMode ? '☀️ Light Mode' : '🌙 Dark Mode'}
                    </button>
                    <button onClick={onLogout} className="w-full py-2 bg-red-900/40 hover:bg-red-600 border border-red-800 rounded-lg text-sm font-bold text-white transition-colors">
                        🚪 Secure Logout
                    </button>
                </div>
            </div>

            <div className="flex-grow overflow-y-auto p-4 md:p-8">
                {activeTab === 'procurement' && <ProcurementPortal />}
                {activeTab === 'finance' && <FinancePortal />}
                {activeTab === 'analytics' && <AnalyticsPortal />}
            </div>
        </div>
    );
}

function ProcurementPortal() {
    const [boqs, setBoqs] = useState([]);
    const [loading, setLoading] = useState(true);
    const [filter, setFilter] = useState('All');
    const [supplierFilter, setSupplierFilter] = useState('All'); // 🚀 NEW: Filter by Supplier

    const fetchBoqs = async () => {
        setLoading(true);
        try {
            const res = await axios.get('https://nestle-finance-command-production.up.railway.app/api/boqs');
            setBoqs(res.data.data || []);
        } catch (err) { console.error(err); }
        finally { setLoading(false); }
    };

    useEffect(() => { fetchBoqs(); }, []);

    const generatePO = async (id) => {
        // 🚀 Optimistic UI Update (Button changes instantly)
        setBoqs(boqs.map(b => b.id === id ? { ...b, status: 'PO Generated: Processing...' } : b));

        try {
            const res = await axios.post(`https://nestle-finance-command-production.up.railway.app/api/boqs/${id}/generate-po`);
            if (res.data.success) {
                fetchBoqs(); // Fetch the real data to confirm
            }
        } catch (err) {
            alert("Failed to generate PO.");
            fetchBoqs(); // Revert state if failed
        }
    };

    const rejectBOQ = async (id) => {
        const reason = window.prompt("Reason for rejection (e.g., Not enough stock, Pricing incorrect):");
        if (!reason) return;
        try {
            await axios.post(`https://nestle-finance-command-production.up.railway.app/api/boqs/${id}/reject`, { reason });
            fetchBoqs();
        } catch (err) { alert("Failed to reject BOQ."); }
    };

    // Generate unique list of suppliers for the dropdown
    const uniqueSuppliers = [...new Set(boqs.map(b => b.vendor_name).filter(Boolean))];

    const filteredBoqs = boqs.filter(b => {
        if (filter === 'Approved' && !b.status.includes('PO Generated')) return false;
        if (filter === 'Pending' && b.status !== 'Pending Review') return false;
        if (filter === 'Rejected' && b.status !== 'Rejected') return false;
        if (supplierFilter !== 'All' && b.vendor_name !== supplierFilter) return false;
        return true;
    });

    return (
        <div className="max-w-7xl mx-auto space-y-6">
            <div className="mb-6 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
                <div>
                    <h2 className="text-3xl font-black text-slate-800 dark:text-white">Procurement Dashboard</h2>
                    <p className="text-slate-500 dark:text-slate-400">Review supplier BOQs and automatically dispatch Official POs.</p>
                </div>
                <div className="flex gap-2 flex-wrap">
                    {/* Supplier Filter Dropdown */}
                    <select value={supplierFilter} onChange={(e) => setSupplierFilter(e.target.value)} className="px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-bold text-slate-600 dark:text-slate-300 outline-none">
                        <option value="All">All Suppliers</option>
                        {uniqueSuppliers.map(sup => <option key={sup} value={sup}>{sup}</option>)}
                    </select>
                    {/* Status Filter Dropdown */}
                    <select value={filter} onChange={(e) => setFilter(e.target.value)} className="px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-bold text-slate-600 dark:text-slate-300 outline-none">
                        <option value="All">All Statuses</option>
                        <option value="Pending">Pending Review</option>
                        <option value="Approved">Approved (PO Sent)</option>
                        <option value="Rejected">Rejected</option>
                    </select>
                    <button onClick={fetchBoqs} className="px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-bold text-slate-600 dark:text-slate-300 shadow-sm hover:shadow">
                        🔄 Refresh
                    </button>
                </div>
            </div>

            <div className="grid grid-cols-1 gap-6">
                {loading ? (
                    <div className="p-12 text-center text-slate-500 font-bold animate-pulse">Loading Supplier Quotes...</div>
                ) : filteredBoqs.length === 0 ? (
                    <div className="p-12 text-center text-slate-500 font-bold bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800">No BOQs match this filter.</div>
                ) : (
                    filteredBoqs.map(boq => {
                        const isApproved = boq.status.includes('PO Generated');
                        const isRejected = boq.status === 'Rejected';

                        return (
                            <div key={boq.id} className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 overflow-hidden flex flex-col md:flex-row">
                                <div className="p-6 md:w-1/3 bg-slate-50 dark:bg-slate-800/50 border-r border-slate-200 dark:border-slate-800 flex flex-col justify-between">
                                    <div>
                                        <p className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-1">Quote Submitted By</p>
                                        <p className="text-xl font-black text-slate-800 dark:text-white mb-1">{boq.vendor_name}</p>
                                        <p className="text-xs text-slate-500 mb-4 font-mono">User ID: {boq.vendor_id || boq.supplier_email}</p>

                                        <p className="text-sm font-medium text-slate-600 dark:text-slate-300">Total Value:</p>
                                        <p className="text-3xl font-black text-blue-600 dark:text-blue-400 mb-4">{formatCurrency(boq.total_amount, boq.currency)}</p>

                                        {isApproved ? (
                                            <div className="p-3 bg-emerald-100 dark:bg-emerald-900/30 rounded-xl border border-emerald-200 dark:border-emerald-800/50">
                                                <p className="text-xs font-bold text-emerald-600 dark:text-emerald-400 uppercase mb-1">✅ PO Dispatched</p>
                                            </div>
                                        ) : isRejected ? (
                                            <div className="p-3 bg-red-100 dark:bg-red-900/30 rounded-xl border border-red-200 dark:border-red-800/50">
                                                <p className="text-xs font-bold text-red-600 dark:text-red-400 uppercase mb-1">❌ Rejected</p>
                                                <p className="text-xs text-red-800 dark:text-red-300">Reason: {boq.rejection_reason}</p>
                                            </div>
                                        ) : (
                                            <span className="px-3 py-1 rounded-full text-xs font-black uppercase bg-amber-100 text-amber-700">Pending Review</span>
                                        )}
                                        <p className="text-xs text-slate-400 mt-4">Uploaded: {new Date(boq.created_at).toLocaleString()}</p>
                                    </div>

                                    {!isApproved && !isRejected && (
                                        <div className="mt-6 flex gap-2">
                                            <button onClick={() => generatePO(boq.id)} className="flex-1 py-3 bg-slate-800 dark:bg-blue-600 hover:bg-black text-white font-black rounded-xl transition-colors">
                                                ⚡ Approve
                                            </button>
                                            <button onClick={() => rejectBOQ(boq.id)} className="flex-1 py-3 bg-red-100 dark:bg-red-900/30 text-red-600 hover:bg-red-200 font-black rounded-xl transition-colors">
                                                Reject
                                            </button>
                                        </div>
                                    )}
                                </div>
                                <div className="p-6 md:w-2/3 flex flex-col">
                                    <div className="flex justify-between items-center mb-3">
                                        <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider">Extracted Line Items</h4>
                                    </div>
                                    <div className="overflow-y-auto max-h-48 border border-slate-100 dark:border-slate-700 rounded-lg">
                                        <table className="w-full text-left text-xs">
                                            <thead className="bg-slate-50 dark:bg-slate-800 sticky top-0">
                                                <tr><th className="p-3 font-bold text-slate-500">Qty</th><th className="p-3 font-bold text-slate-500">Item</th><th className="p-3 font-bold text-slate-500 text-right">Unit Price</th><th className="p-3 font-bold text-slate-500 text-right">Total</th></tr>
                                            </thead>
                                            <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                                                {boq.line_items && boq.line_items.map((item, idx) => (
                                                    <tr key={idx} className="hover:bg-slate-50 dark:hover:bg-slate-800/30">
                                                        <td className="p-3 text-slate-700 dark:text-slate-300">{item.qty}</td>
                                                        <td className="p-3 font-medium text-slate-800 dark:text-slate-100">{item.description}</td>
                                                        <td className="p-3 text-right text-slate-600 dark:text-slate-400">{formatCurrency(item.unitPrice, boq.currency)}</td>
                                                        <td className="p-3 text-right font-bold text-slate-800 dark:text-slate-200">{formatCurrency(item.amount, boq.currency)}</td>
                                                    </tr>
                                                ))}
                                            </tbody>
                                        </table>
                                    </div>
                                </div>
                            </div>
                        );
                    })
                )}
            </div>
        </div>
    );
}

function FinancePortal() {
    const [records, setRecords] = useState([]);
    const [loading, setLoading] = useState(true);
    const [filter, setFilter] = useState('All');
    const [expandedRow, setExpandedRow] = useState(null);

    const fetchRecords = async () => {
        setLoading(true);
        try {
            const res = await axios.get('https://nestle-finance-command-production.up.railway.app/api/reconciliations');
            setRecords(res.data.data || []);
        } catch (err) { console.error(err); } finally { setLoading(false); }
    };

    useEffect(() => { fetchRecords(); }, []);

    const handleManualOverride = async (id, decision) => {
        // 🚀 Ensure it sets exactly to "Approved" or "Rejected"
        try {
            await axios.patch(`https://nestle-finance-command-production.up.railway.app/api/reconciliations/${id}`, { newStatus: decision });
            fetchRecords();
        } catch (err) { alert("Failed to update status."); }
    };

    const filteredRecords = records.filter(r => {
        if (filter === 'All') return true;
        if (filter === 'Pending' && r.match_status.includes('Reject')) return true;
        if (filter === 'Approved' && r.match_status === 'Approved') return true;
        return false;
    });

    return (
        <div className="max-w-7xl mx-auto space-y-6">
            <div className="mb-6 flex flex-col sm:flex-row sm:items-end justify-between gap-4">
                <div>
                    <h2 className="text-3xl font-black text-slate-800 dark:text-white">Finance Review Queue</h2>
                    <p className="text-slate-500 dark:text-slate-400">Expand rows to download submitted documents and resolve discrepancies.</p>
                </div>
                <div className="flex gap-2">
                    <select value={filter} onChange={(e) => setFilter(e.target.value)} className="px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-bold text-slate-600 dark:text-slate-300 outline-none">
                        <option value="All">All Documents</option>
                        <option value="Pending">Needs Review (Discrepancy)</option>
                        <option value="Approved">Approved</option>
                    </select>
                    <button onClick={fetchRecords} className="px-4 py-2 bg-white dark:bg-slate-800 border border-slate-200 dark:border-slate-700 rounded-lg text-sm font-bold text-slate-600 dark:text-slate-300 shadow-sm hover:shadow">
                        🔄 Refresh Queue
                    </button>
                </div>
            </div>

            <div className="bg-white dark:bg-slate-900 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800 overflow-hidden overflow-x-auto">
                {loading ? (
                    <div className="p-12 text-center text-slate-500 font-bold animate-pulse">Fetching Secure Database Records...</div>
                ) : (
                    <table className="w-full text-left text-sm min-w-[800px]">
                        <thead className="bg-slate-50 dark:bg-slate-800/50 text-slate-500 dark:text-slate-400 uppercase text-xs font-bold tracking-wider">
                            <tr>
                                <th className="p-4 border-b border-slate-200 dark:border-slate-800">Date</th>
                                <th className="p-4 border-b border-slate-200 dark:border-slate-800">Vendor</th>
                                <th className="p-4 border-b border-slate-200 dark:border-slate-800">Invoice / PO</th>
                                <th className="p-4 border-b border-slate-200 dark:border-slate-800">Inv Total</th>
                                <th className="p-4 border-b border-slate-200 dark:border-slate-800">PO Total</th>
                                <th className="p-4 border-b border-slate-200 dark:border-slate-800">Status</th>
                                <th className="p-4 border-b border-slate-200 dark:border-slate-800 text-right">Action</th>
                            </tr>
                        </thead>
                        <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                            {filteredRecords.map((r) => (
                                <>
                                    <tr key={r.id} className="hover:bg-slate-50 dark:hover:bg-slate-800/30">
                                        <td className="p-4 font-mono text-xs text-slate-400">{new Date(r.processed_at).toLocaleDateString()}</td>
                                        <td className="p-4 font-bold text-slate-800 dark:text-slate-200 cursor-pointer" onClick={() => setExpandedRow(expandedRow === r.id ? null : r.id)}>
                                            {r.vendor_name || 'Unknown'} <span className="text-blue-500 ml-2 text-xs">👁️ Verify Docs</span>
                                        </td>
                                        <td className="p-4">
                                            <div className="text-blue-600 dark:text-blue-400 font-medium text-xs">{r.invoice_number}</div>
                                            <div className="text-purple-600 dark:text-purple-400 font-medium text-xs">{r.po_number}</div>
                                        </td>
                                        <td className="p-4 font-black text-slate-700 dark:text-slate-300">${r.invoice_total}</td>
                                        <td className="p-4 font-black text-slate-700 dark:text-slate-300">${r.po_total}</td>
                                        <td className="p-4">
                                            <span className={`px-3 py-1 rounded-full text-xs font-black uppercase ${r.match_status === 'Approved' ? 'bg-emerald-100 text-emerald-700' : 'bg-red-100 text-red-700'}`}>
                                                {r.match_status}
                                            </span>
                                        </td>
                                        <td className="p-4 text-right space-x-2">
                                            <button onClick={() => handleManualOverride(r.id, 'Approved')} className="px-3 py-1 bg-slate-100 dark:bg-slate-800 hover:bg-emerald-500 hover:text-white font-bold rounded text-xs transition-colors">Approve</button>
                                            <button onClick={() => handleManualOverride(r.id, 'Rejected')} className="px-3 py-1 bg-slate-100 dark:bg-slate-800 hover:bg-red-500 hover:text-white font-bold rounded text-xs transition-colors">Reject</button>
                                        </td>
                                    </tr>
                                    {/* 🚀 EXTANDED ROW: Download Options for Finance */}
                                    {expandedRow === r.id && (
                                        <tr className="bg-slate-50 dark:bg-slate-800/20">
                                            <td colSpan="7" className="p-6 border-b border-slate-200 dark:border-slate-800">
                                                <div className="grid grid-cols-2 gap-6">
                                                    <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
                                                        <div className="flex justify-between items-center border-b border-slate-100 dark:border-slate-800 pb-3 mb-3">
                                                            <h4 className="font-bold text-slate-700 dark:text-slate-300">Invoice Document</h4>
                                                            <button onClick={() => handlePrintDocument('Invoice Data Extract', r.invoice_data)} className="text-xs font-bold text-white bg-blue-500 hover:bg-blue-600 px-3 py-1 rounded-lg">📥 Download Extract</button>
                                                        </div>
                                                        <p className="text-sm"><strong>Total:</strong> ${r.invoice_total}</p>
                                                        <p className="text-sm"><strong>Timeline:</strong> {r.timeline_status}</p>
                                                    </div>
                                                    <div className="bg-white dark:bg-slate-900 p-4 rounded-xl border border-slate-200 dark:border-slate-700">
                                                        <div className="flex justify-between items-center border-b border-slate-100 dark:border-slate-800 pb-3 mb-3">
                                                            <h4 className="font-bold text-slate-700 dark:text-slate-300">Purchase Order Match</h4>
                                                            <button onClick={() => handlePrintDocument('Purchase Order Extract', r.po_data)} className="text-xs font-bold text-white bg-purple-500 hover:bg-purple-600 px-3 py-1 rounded-lg">📥 Download Extract</button>
                                                        </div>
                                                        <p className="text-sm"><strong>PO Total:</strong> ${r.po_total}</p>
                                                        <p className="text-sm"><strong>Variance:</strong> <span className={r.invoice_total === r.po_total ? 'text-emerald-500' : 'text-red-500'}>${Math.abs(r.invoice_total - r.po_total).toFixed(2)}</span></p>
                                                    </div>
                                                </div>
                                            </td>
                                        </tr>
                                    )}
                                </>
                            ))}
                        </tbody>
                    </table>
                )}
            </div>
        </div>
    );
}

function AnalyticsPortal() {
    const [stats, setStats] = useState({ total: 0, approved: 0, rejected: 0, value: 0 });
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchStats = async () => {
            try {
                const res = await axios.get('https://nestle-finance-command-production.up.railway.app/api/reconciliations');
                const data = res.data.data || [];
                const approved = data.filter(r => r.match_status && r.match_status.includes('Approve')).length;
                const rejected = data.filter(r => r.match_status && r.match_status.includes('Reject')).length;
                const totalValue = data.reduce((acc, curr) => acc + (Number(curr.invoice_total) || 0), 0);
                setStats({ total: data.length, approved, rejected, value: totalValue });
            } catch (err) { console.error(err); } finally { setLoading(false); }
        };
        fetchStats();
    }, []);

    return (
        <div className="max-w-7xl mx-auto space-y-6">
            <div className="mb-6">
                <h2 className="text-3xl font-black text-slate-800 dark:text-white">Platform Analytics</h2>
                <p className="text-slate-500 dark:text-slate-400">High-level view of AI throughput and financial processing.</p>
            </div>

            {loading ? (
                <div className="p-12 text-center text-slate-500 font-bold animate-pulse">Calculating Live Metrics...</div>
            ) : (
                <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
                    <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
                        <p className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-2">Total Documents</p>
                        <p className="text-5xl font-black text-blue-600 dark:text-blue-400">{stats.total}</p>
                    </div>
                    <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
                        <p className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-2">Auto-Approval Rate</p>
                        <p className="text-5xl font-black text-emerald-500 dark:text-emerald-400">
                            {stats.total > 0 ? Math.round((stats.approved / stats.total) * 100) : 0}%
                        </p>
                        <p className="text-xs text-slate-500 mt-2 font-medium">{stats.approved} Approved / {stats.rejected} Rejected</p>
                    </div>
                    <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl shadow-sm border border-slate-200 dark:border-slate-800">
                        <p className="text-sm font-bold text-slate-400 uppercase tracking-wider mb-2">Total Value Processed</p>
                        <p className="text-4xl font-black text-slate-800 dark:text-slate-100 mt-2">${stats.value.toLocaleString(undefined, { minimumFractionDigits: 2 })}</p>
                    </div>
                </div>
            )}
        </div>
    );
}